name: document-issue-dev
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8,<3.12.0a0
  - frictionless>5
  - frictionless[json]
  - pandas
  - pytest
  - flake8
  - black
  - tomli
  - pytest-pretty
  - pypdf
  - pip
  - pip:
      - polyfactory
      - -e packages/document-issue 
      - -e packages/document-issue-io
      - -e packages/document-issue-io[dev]
      - -e packages/document-issue-api
      - -e packages/document-issue-ui