name: document-issue-dev
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - numpy
  - pandas
  - dataclasses
  - pandoc
  - pydantic
  - tabulate
  - toml
  - Jinja2
  - click
  - stringcase
  - pytest
  - black
  - jupytext # authoring docs
  - jupyterlab # authoring docs
  - jupyterbook # docs
  - autodoc-pydantic # docs
  - erdantic # docs
  - sphinxcontrib-mermaid # docs
  - sphinx-autoapi # docs
  - pip
  - pip:
      - jsonschema2md
      - sphinx-github-changelog
      - nb-black
