name: document-issue-dev
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8,<3.12.0a0
  - frictionless
  - pandas
  - pytest
  - flake8
  - black
  - tomli
  - pytest-pretty
  - pip
  - pip:
      - polyfactory
      - -e packages/document-issue 
      - -e packages/document-issue-io
      - -e packages/document-issue-api