name: document-issue-dev
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8,<3.12.0a0
  - pytest
  - black
  - tomli
  - pytest-pretty
  - pip
  - pip:
      - polyfactory
      - jupyter-black
