[project]
channels = ["conda-forge"]
platforms = ["linux-64"]
name = "document-issue"

[dependencies]
python = ">=3.8"
rich = ">=13.9.3,<14"
pytest = "*"
pre-commit = ">=4.0.1,<5"
ipykernel = ">=6.29.5,<7"
erdantic = "*"
r-tinytex = "*"
pandas = "*"
quarto = "<1.7"
ruff = "*"
# mysql-connector-python = "*" # NOTE: conda version older so not using...
# eralchemy = "*" # TODO: figure out why this isn't working...

[pypi-dependencies]
document-issue-io = { path = "packages/document-issue-io", extras = [
    "dev",
], editable = true }
document-issue = { path = "packages/document-issue", editable = true }
document-issue-api = { path = "packages/document-issue-api", editable = true }
document-issue-ui = { path = "packages/document-issue-ui", editable = true }
bep = { path = "packages/bep", editable = true }
pytest-examples = ">=0.0.15, <0.0.16"
mysql-connector-python = "*" # TODO: add mfdb
# ipyautoui = { path = "../../ipyautoui", editable = true } # DEV ONLY

[feature.document-issue.dependencies]
python = ">=3.8"
pytest = "*"

[feature.document-issue.pypi-dependencies]
document-issue = { path = "packages/document-issue", editable = true }
bep = { path = "packages/bep", editable = true }

[feature.document-issue.tasks]
test-document-issue = { cmd = "pytest", cwd = "packages/document-issue" }

[environments]
document-issue = { features = ["document-issue"], no-default-feature = true }
dashboard = ["dashboard"]

[feature.dashboard.dependencies]
nodejs = "*"

[tasks]
test-document-issue-quarto = { cmd = "pytest", cwd = "packages/document-issue-quarto" }
test-document-issue-io = { cmd = "pytest", cwd = "packages/document-issue-io" }
test-document-issue-api = { cmd = "pytest", cwd = "packages/document-issue-api", env = { SQLALCHEMY_WARN_20 = "1" } }
test-bep = { cmd = "pytest", cwd = "packages/bep" }
update-examples = { cmd = "pytest --update-examples", cwd = "packages/document-issue-io" }
update-quarto-extensions = "tar -czvf packages/document-issue-io/src/document_issue_io/templates/document-issue-quarto.tar.gz -C packages/document-issue-quarto _extensions"
build-docs = { cmd = "quarto render .", cwd = "docs" } #, depends-on = ["test-document-issue-io"]
preview-docs = { cmd = "quarto preview .", cwd = "docs" }
demo-ui = { cmd = "voila demo.ipynb", cwd = "packages/document-issue-ui" }
jlab-ui = { cmd = "jupyter lab demo.ipynb", cwd = "packages/document-issue-ui" }
demo-api = { depends-on = [
    "test-document-issue",
    "test-document-issue-quarto",
    "test-document-issue-io",
    "test-document-issue-api",
] }
tests = { depends-on = [
    "test-document-issue",
    "test-document-issue-quarto",
    "test-document-issue-io",
    "test-document-issue-api",
] }
lint = "ruff check --fix"
format = "ruff format"
get-project-roles = { cmd = "python get-project-roles.py", cwd = "packages/bep/scripts" }
