[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "document-issue-api"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [{ name = "J Gunstone", email = "j.gunstone@maxfordham.com" }]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "uvicorn",
    "fastapi",
    "pydantic>2",
    "pydantic-settings",
    "sqlalchemy>2",
    "httpx",
    "Jinja2",
    "stringcase",
    "PyYAML",
    "pillow",
    "tabulate",
    "python-dotenv",
]

[project.urls]
Documentation = "https://github.com/unknown/document-issue-api#readme"
Issues = "https://github.com/unknown/document-issue-api/issues"
Source = "https://github.com/unknown/document-issue-api"

[tool.hatch.version]
source = "vcs"
raw-options = { root = "../.." }
