name: document-issue-dev
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - pytest
  - black
  - nb_black
  # - jupytext # authoring docs
  # - jupyterlab # authoring docs
  # - jupyter-book # docs
  # - autodoc-pydantic # docs
  # - erdantic # docs
  # - sphinxcontrib-mermaid # docs
  # - sphinx-autoapi # docs
  - pip
  - pip:
      - polyfactory
      # - jsonschema2md
      # - sphinx-github-changelog
