project:
  type: book
  pre-render: prepare.py
book:
  title: "Spec100"
  author: "Norah Jones"
  date: "5/17/2024"
  chapters:
    - issue.md
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  pdf: default

footer-logo: logo.png
title-page: title-page.pdf