[project]
authors = [{name = "jgunstone", email = "j.gunstone@maxfordham.com"}]
dependencies = ["pydantic", "pydantic-settings>=2.8.1,<3"]
description = "Add a short description here"
name = "bep"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
bep = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
pydantic-settings = ">=2.8.1,<3"

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
pythonpath = "tests"