project:
  type: book
book:
  chapters:
    - index.qmd
    - document.md
    - heating.qmd
project_name: A Max Fordham Project
document_description: A description of the document that is important
footer-logo: logo.png
title-page: title-page.pdf
classoption: portrait
papersize: a4
toc: false