name: document-issue-docs
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8,<3.12.0a0
  - black
  - tomli
  - jupytext # authoring docs
  - jupyterlab # authoring docs
  - jupyter-book # docs
  - autodoc-pydantic # docs
  - erdantic # docs
  - sphinxcontrib-mermaid # docs
  - sphinx-autoapi # docs
  - pip
  - pip:
      - jupyter-black
      - jsonschema2md
      - sphinx-github-changelog
