# TODO: setup auto-update pixi.lock https://pixi.sh/latest/advanced/updates_github_actions/#how-to-use

name: Test, Lint and Build Docs

on:
    push:
      branches: [main]
    pull_request:
      branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
            
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.3
        with:
            manifest-path: pixi.toml
            pixi-version: v0.43.1
            cache: true
            cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - run: | 
          quarto install tinytex
        shell: pixi run bash -e {0} # https://pixi.sh/latest/advanced/github_actions/#custom-shell-wrapper
      - run: pixi run tests
      - run: pixi run build-docs
      - name: Push docs to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/_site
